package fsm2;

public enum States {
	UEBERWACHE, 
	HUMIDITY_LOW, 
	TOR_SCHLIESSEN, 
	PUMPEN_EINSCHALTEN, 
	FEHLER_FESTGESTELLT,
	TOR_ZU_PUMPEN_AN, 
	TOR_OEFFNEN_PUMPEN_ABSCHALTEN, 
	FEHLER, 
	DUMMY
}
